{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "7ad24c30",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-07-30 11:19:48.488 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.489 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.489 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.490 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.491 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.492 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.493 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.495 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.496 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.497 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.498 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.499 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.500 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.501 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.502 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.503 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.504 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.505 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.506 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.507 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.508 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.509 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.510 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.510 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.511 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:48.512 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "[*********************100%***********************]  5 of 5 completed\n",
      "2026-07-30 11:19:49.455 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.456 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.457 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.457 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.458 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.458 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.459 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.459 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.462 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.462 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.463 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.464 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.464 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.465 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.465 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.466 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.466 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.479 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.479 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.480 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.481 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.481 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.482 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.482 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.483 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.496 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.496 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.497 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.497 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-30 11:19:49.498 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import yfinance as yf\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "\n",
    "st.title(\"📈 Portfolio Optimization Dashboard\")\n",
    "\n",
    "# Sidebar inputs\n",
    "assets_text = st.sidebar.text_input(\"Enter Assets (comma separated):\", \"AAPL,MSFT,TSLA,NVDA\")\n",
    "num_portfolios = st.sidebar.slider(\"Number of Portfolios:\", 1000, 20000, 5000, 1000)\n",
    "risk_free_rate = st.sidebar.number_input(\"Risk-Free Rate (%):\", value=2.0, step=0.1)\n",
    "benchmark_ticker = st.sidebar.text_input(\"Benchmark Ticker:\", \"^GSPC\")\n",
    "\n",
    "assets = [a.strip() for a in assets_text.split(\",\")]\n",
    "\n",
    "# Download data\n",
    "data = yf.download(assets + [benchmark_ticker], start=\"2020-01-01\", end=\"2026-01-01\")\n",
    "\n",
    "# ✅ Handle Adj Close vs Close\n",
    "if \"Adj Close\" in data.columns:\n",
    "    prices = data[\"Adj Close\"][assets]\n",
    "    benchmark_prices = data[\"Adj Close\"][benchmark_ticker]\n",
    "else:\n",
    "    prices = data[\"Close\"][assets]\n",
    "    benchmark_prices = data[\"Close\"][benchmark_ticker]\n",
    "\n",
    "returns = prices.pct_change().dropna()\n",
    "benchmark_returns = benchmark_prices.pct_change().dropna()\n",
    "\n",
    "# Portfolio statistics\n",
    "mean_returns = returns.mean().to_numpy()\n",
    "cov_matrix = returns.cov().to_numpy()\n",
    "\n",
    "results = np.zeros((3, num_portfolios))\n",
    "weights_record = []\n",
    "rf = risk_free_rate / 100\n",
    "\n",
    "for i in range(num_portfolios):\n",
    "    weights = np.random.dirichlet(np.ones(len(assets)))\n",
    "    port_return = np.dot(weights, mean_returns)\n",
    "    port_std = np.sqrt(weights @ cov_matrix @ weights)\n",
    "    sharpe = (port_return - rf) / port_std\n",
    "    results[0,i] = port_return\n",
    "    results[1,i] = port_std\n",
    "    results[2,i] = sharpe\n",
    "    weights_record.append(weights)\n",
    "\n",
    "# Best portfolio\n",
    "max_sharpe_idx = results[2].argmax()\n",
    "best_return, best_std, best_sharpe = results[:, max_sharpe_idx]\n",
    "best_weights = weights_record[max_sharpe_idx]\n",
    "\n",
    "# Efficient frontier plot\n",
    "fig_frontier = px.scatter(x=results[1,:], y=results[0,:], color=results[2,:],\n",
    "                          labels={'x':'Risk (Std Dev)','y':'Return','color':'Sharpe Ratio'},\n",
    "                          title=\"Efficient Frontier\")\n",
    "fig_frontier.add_scatter(x=[best_std], y=[best_return], mode='markers',\n",
    "                         marker=dict(color='red', size=12, symbol='star'),\n",
    "                         name='Best Portfolio')\n",
    "st.plotly_chart(fig_frontier)\n",
    "\n",
    "# Best portfolio weights\n",
    "st.subheader(\"🔑 Best Portfolio Weights\")\n",
    "st.dataframe(pd.DataFrame({'Asset': assets, 'Weight': best_weights}))\n",
    "st.write(f\"**Mean Return:** {best_return:.4f}, **Std Dev:** {best_std:.4f}, **Sharpe:** {best_sharpe:.4f}\")\n",
    "\n",
    "# Benchmark comparison\n",
    "st.subheader(\"📊 Portfolio vs Benchmark Cumulative Returns\")\n",
    "portfolio_returns = (returns @ best_weights)\n",
    "portfolio_cum = (1 + portfolio_returns).cumprod()\n",
    "benchmark_cum = (1 + benchmark_returns).cumprod()\n",
    "\n",
    "fig_benchmark = go.Figure()\n",
    "fig_benchmark.add_trace(go.Scatter(y=portfolio_cum, x=portfolio_cum.index,\n",
    "                                   mode='lines', name='Optimized Portfolio'))\n",
    "fig_benchmark.add_trace(go.Scatter(y=benchmark_cum, x=benchmark_cum.index,\n",
    "                                   mode='lines', name=benchmark_ticker))\n",
    "fig_benchmark.update_layout(title=\"Portfolio vs Benchmark Cumulative Returns\",\n",
    "                            xaxis_title=\"Date\", yaxis_title=\"Cumulative Return\")\n",
    "st.plotly_chart(fig_benchmark)\n",
    "\n",
    "# Rolling Sharpe ratio\n",
    "st.subheader(\"📉 Rolling Sharpe Ratio (90-day window)\")\n",
    "rolling_window = 90\n",
    "rolling_sharpe = (portfolio_returns.rolling(rolling_window).mean() - rf/252) / \\\n",
    "                 portfolio_returns.rolling(rolling_window).std()\n",
    "\n",
    "fig_sharpe = go.Figure()\n",
    "fig_sharpe.add_trace(go.Scatter(y=rolling_sharpe, x=rolling_sharpe.index,\n",
    "                                mode='lines', name='Rolling Sharpe'))\n",
    "fig_sharpe.update_layout(title=\"Rolling Sharpe Ratio\",\n",
    "                         xaxis_title=\"Date\", yaxis_title=\"Sharpe Ratio\")\n",
    "st.plotly_chart(fig_sharpe)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fb6d47c7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
